### ISSUE TITLE
Consider performance with regards to ChildLogger

### ISSUE THREAD

**Issue by eropple** [tilfin/ougai#57]
Not a critical thing, but I noticed that calls to loggers through ChildLogger are recursive. Might be worth having each ChildLogger record its parent and a fresh copy of all fields to reduce these; right now I've got four-level-deep child chains in places and while it isn't a performance concern yet, I can totally see it becoming an issue.

**Comment by tilfin** [comment]
Yes, I knew the cost of child logger chain, it is especially Hash merge. But copying with_fields of the parent to child's at first forces parent logger to have the refercences of children and to propagate their updates to children. 
I think a logger should be stable rather than be fast. That is the trade-off of the stable and the speed about this issue.

By the way I came up with duplicating a child logger if with_fields of itself and its middle loggers can be freezed.

```ruby
class Ougai::ChildLogger
  def dup_with_fields(fields = {})
    @parent.child(@with_fields.merge(fields))
  end
end
```

**Comment by tilfin** [comment]
Please feel free to open this if there is something.
