### ISSUE TITLE
Fields order

### ISSUE THREAD

**Issue by flexoid** [tilfin/ougai#72]
Hi! 

First of all, thanks for a great gem.

Following code

```ruby
logger = Ougai::Logger.new(STDOUT)
logger.with_fields = { app: 'myapp' }

request_logger = logger.child(request_id: "dh17gd816gfub")
request_logger.info("completed", ms: 12345, status: 200)
```

Produces
```
{"name":"rails_console","hostname":"...","pid":...,"level":30,"time":"...","v":0,"msg":"completed","ms":12345,"status":200,"request_id":"dh17gd816gfub","app":"myapp"}
```

But I expect something like this
```
{"name":"rails_console","hostname":"...","pid":...,"level":30,"time":"...","msg":"completed","app":"myapp","request_id":"dh17gd816gfub","ms":12345,"status":200,"v":0}
```

I know that JSON object structure natively is not ordered. But it looks logical to me to preserve fields order when consecutively adding them with `with_fields` and `child`. It's also much more convenient for human readability of the logs, when more "generic" fields come before more specific.

Such libraries as `pino` for nodejs and `zerolog` for golang keep fields ordered.

I haven't check yet, but it even looks like a regression [here](https://github.com/tilfin/ougai/commit/114979820e3e3e3a988d6aafddd0d5fa61834c40), so should be quite easy to fix.

Thank you.

**Comment by tilfin** [comment]
Hello, @flexoid 

I understand what you think. On the other hand, for example, it is not programatical that `v` is placed last but I feel it to be better too. I also think some people prefer the reverse format to place detail info on the head of log because a JSONLine log needs wide screen.

To customize a formatter can change the orders of basic information (like name, hosname, pid,... ), But there is no way to customize some `with_fields` merging order. so the latter way should be provided.
