### ISSUE TITLE
Inherit from Mono Logger

### ISSUE THREAD

**Issue by tmedford** [tilfin/ougai#74]
How would we make ougai inherit from mono logger as to protect against trapped threads. 
![image](https://user-images.githubusercontent.com/4482381/54869301-f0024c80-4d6c-11e9-80b5-94023ebb25ce.png)

**Comment by tmedford** [comment]
Confirmed, ougai logger does not protect agains trap context.

**Comment by tilfin** [comment]
I have not confirmed this behavior. I propose the solution how you directly create LocklessLogDevice and set it the first argument of `Ougai::Logger.new`. https://github.com/steveklabnik/mono_logger/blob/master/lib/mono_logger.rb#L42

**Comment by SkipKayhil** [comment]
Hey @tilfin,

I wanted to add some more information to help explain the issue and how to reproduce it (and my solutions in case anyone comes across this in the future)

You can reproduce it with the following snippet:
```ruby
require 'ougai'

logger = Ougai::Logger.new(STDOUT)

trap(:USR1) do
  logger.info("Logging in a trap")
end

Process.kill("USR1", $$)
```

I also tried your solution:
```ruby
require 'ougai'
require 'mono_logger'

log_device = MonoLogger::LocklessLogDevice.new(STDOUT)
logger = Ougai::Logger.new(log_device)

trap(:USR1) do
  logger.info("Logging in a trap")
end

Process.kill("USR1", $$)
```
However, I believe this doesn't work because the [base ruby Logger class always creates a LogDevice](https://github.com/ruby/ruby/blob/d0693391103672b7fc3976e5ae8ae414059b3e97/lib/logger.rb#L389)

My current solutions are overriding the `@logdev` instance variable:
```ruby
require 'ougai'
require 'mono_logger'

log_device = MonoLogger::LocklessLogDevice.new(STDOUT)
logger = Ougai::Logger.new(STDOUT)
logger.instance_variable_set("@logdev", log_device)

trap(:USR1) do
  logger.info("Logging in a trap")
end

Process.kill("USR1", $$)
```
or subclassing `Ougai::Logger` to set the `@logdev` variable after `super`:
```ruby
require 'ougai'
require 'mono_logger'

class CustomLogger < Ougai::Logger
  def initialize(logdev, **)
    super

    @logdev = MonoLogger::LocklessLogDevice.new(logdev)
  end
end

logger = CustomLogger.new(STDOUT)

trap(:USR1) do
  logger.info("Logging in a trap")
end

Process.kill("USR1", $$)
```
